/* probe.generated.c --- GENERATED FILE, DO NOT EDIT.
 *
 * Produced by tools/native-abi/generate.py.  This translation unit is compiled
 * against the canonical CNA headers by tools/native-abi/verify.sh; it never
 * ships and is never linked into CNA-Lisp.
 */
#include <CNA/C/cna.h>
#include <stddef.h>
#include <stdint.h>

/* --- struct layout: every size, alignment, field offset and field size --- */
_Static_assert(sizeof(CNA_ErrorInfo) == 24, "CNA_ErrorInfo size");
_Static_assert(_Alignof(CNA_ErrorInfo) == 8, "CNA_ErrorInfo alignment");
_Static_assert(offsetof(CNA_ErrorInfo, struct_size) == 0, "CNA_ErrorInfo.struct_size offset");
_Static_assert(sizeof(((CNA_ErrorInfo *)0)->struct_size) == 4, "CNA_ErrorInfo.struct_size size");
_Static_assert(offsetof(CNA_ErrorInfo, struct_version) == 4, "CNA_ErrorInfo.struct_version offset");
_Static_assert(sizeof(((CNA_ErrorInfo *)0)->struct_version) == 4, "CNA_ErrorInfo.struct_version size");
_Static_assert(offsetof(CNA_ErrorInfo, result) == 8, "CNA_ErrorInfo.result offset");
_Static_assert(sizeof(((CNA_ErrorInfo *)0)->result) == 4, "CNA_ErrorInfo.result size");
_Static_assert(offsetof(CNA_ErrorInfo, category) == 12, "CNA_ErrorInfo.category offset");
_Static_assert(sizeof(((CNA_ErrorInfo *)0)->category) == 4, "CNA_ErrorInfo.category size");
_Static_assert(offsetof(CNA_ErrorInfo, message_byte_length) == 16, "CNA_ErrorInfo.message_byte_length offset");
_Static_assert(sizeof(((CNA_ErrorInfo *)0)->message_byte_length) == 8, "CNA_ErrorInfo.message_byte_length size");

_Static_assert(sizeof(CNA_StringView) == 16, "CNA_StringView size");
_Static_assert(_Alignof(CNA_StringView) == 8, "CNA_StringView alignment");
_Static_assert(offsetof(CNA_StringView, data) == 0, "CNA_StringView.data offset");
_Static_assert(sizeof(((CNA_StringView *)0)->data) == 8, "CNA_StringView.data size");
_Static_assert(offsetof(CNA_StringView, byte_length) == 8, "CNA_StringView.byte_length offset");
_Static_assert(sizeof(((CNA_StringView *)0)->byte_length) == 8, "CNA_StringView.byte_length size");

_Static_assert(sizeof(CNA_Color) == 4, "CNA_Color size");
_Static_assert(_Alignof(CNA_Color) == 1, "CNA_Color alignment");
_Static_assert(offsetof(CNA_Color, r) == 0, "CNA_Color.r offset");
_Static_assert(sizeof(((CNA_Color *)0)->r) == 1, "CNA_Color.r size");
_Static_assert(offsetof(CNA_Color, g) == 1, "CNA_Color.g offset");
_Static_assert(sizeof(((CNA_Color *)0)->g) == 1, "CNA_Color.g size");
_Static_assert(offsetof(CNA_Color, b) == 2, "CNA_Color.b offset");
_Static_assert(sizeof(((CNA_Color *)0)->b) == 1, "CNA_Color.b size");
_Static_assert(offsetof(CNA_Color, a) == 3, "CNA_Color.a offset");
_Static_assert(sizeof(((CNA_Color *)0)->a) == 1, "CNA_Color.a size");

_Static_assert(sizeof(CNA_Rectangle) == 16, "CNA_Rectangle size");
_Static_assert(_Alignof(CNA_Rectangle) == 4, "CNA_Rectangle alignment");
_Static_assert(offsetof(CNA_Rectangle, x) == 0, "CNA_Rectangle.x offset");
_Static_assert(sizeof(((CNA_Rectangle *)0)->x) == 4, "CNA_Rectangle.x size");
_Static_assert(offsetof(CNA_Rectangle, y) == 4, "CNA_Rectangle.y offset");
_Static_assert(sizeof(((CNA_Rectangle *)0)->y) == 4, "CNA_Rectangle.y size");
_Static_assert(offsetof(CNA_Rectangle, width) == 8, "CNA_Rectangle.width offset");
_Static_assert(sizeof(((CNA_Rectangle *)0)->width) == 4, "CNA_Rectangle.width size");
_Static_assert(offsetof(CNA_Rectangle, height) == 12, "CNA_Rectangle.height offset");
_Static_assert(sizeof(((CNA_Rectangle *)0)->height) == 4, "CNA_Rectangle.height size");

_Static_assert(sizeof(CNA_Point) == 8, "CNA_Point size");
_Static_assert(_Alignof(CNA_Point) == 4, "CNA_Point alignment");
_Static_assert(offsetof(CNA_Point, x) == 0, "CNA_Point.x offset");
_Static_assert(sizeof(((CNA_Point *)0)->x) == 4, "CNA_Point.x size");
_Static_assert(offsetof(CNA_Point, y) == 4, "CNA_Point.y offset");
_Static_assert(sizeof(((CNA_Point *)0)->y) == 4, "CNA_Point.y size");

_Static_assert(sizeof(CNA_Vector2) == 8, "CNA_Vector2 size");
_Static_assert(_Alignof(CNA_Vector2) == 4, "CNA_Vector2 alignment");
_Static_assert(offsetof(CNA_Vector2, x) == 0, "CNA_Vector2.x offset");
_Static_assert(sizeof(((CNA_Vector2 *)0)->x) == 4, "CNA_Vector2.x size");
_Static_assert(offsetof(CNA_Vector2, y) == 4, "CNA_Vector2.y offset");
_Static_assert(sizeof(((CNA_Vector2 *)0)->y) == 4, "CNA_Vector2.y size");

_Static_assert(sizeof(CNA_Viewport) == 24, "CNA_Viewport size");
_Static_assert(_Alignof(CNA_Viewport) == 4, "CNA_Viewport alignment");
_Static_assert(offsetof(CNA_Viewport, x) == 0, "CNA_Viewport.x offset");
_Static_assert(sizeof(((CNA_Viewport *)0)->x) == 4, "CNA_Viewport.x size");
_Static_assert(offsetof(CNA_Viewport, y) == 4, "CNA_Viewport.y offset");
_Static_assert(sizeof(((CNA_Viewport *)0)->y) == 4, "CNA_Viewport.y size");
_Static_assert(offsetof(CNA_Viewport, width) == 8, "CNA_Viewport.width offset");
_Static_assert(sizeof(((CNA_Viewport *)0)->width) == 4, "CNA_Viewport.width size");
_Static_assert(offsetof(CNA_Viewport, height) == 12, "CNA_Viewport.height offset");
_Static_assert(sizeof(((CNA_Viewport *)0)->height) == 4, "CNA_Viewport.height size");
_Static_assert(offsetof(CNA_Viewport, min_depth) == 16, "CNA_Viewport.min_depth offset");
_Static_assert(sizeof(((CNA_Viewport *)0)->min_depth) == 4, "CNA_Viewport.min_depth size");
_Static_assert(offsetof(CNA_Viewport, max_depth) == 20, "CNA_Viewport.max_depth offset");
_Static_assert(sizeof(((CNA_Viewport *)0)->max_depth) == 4, "CNA_Viewport.max_depth size");

_Static_assert(sizeof(CNA_GameTime) == 24, "CNA_GameTime size");
_Static_assert(_Alignof(CNA_GameTime) == 8, "CNA_GameTime alignment");
_Static_assert(offsetof(CNA_GameTime, total_game_time_ticks) == 0, "CNA_GameTime.total_game_time_ticks offset");
_Static_assert(sizeof(((CNA_GameTime *)0)->total_game_time_ticks) == 8, "CNA_GameTime.total_game_time_ticks size");
_Static_assert(offsetof(CNA_GameTime, elapsed_game_time_ticks) == 8, "CNA_GameTime.elapsed_game_time_ticks offset");
_Static_assert(sizeof(((CNA_GameTime *)0)->elapsed_game_time_ticks) == 8, "CNA_GameTime.elapsed_game_time_ticks size");
_Static_assert(offsetof(CNA_GameTime, is_running_slowly) == 16, "CNA_GameTime.is_running_slowly offset");
_Static_assert(sizeof(((CNA_GameTime *)0)->is_running_slowly) == 1, "CNA_GameTime.is_running_slowly size");
_Static_assert(offsetof(CNA_GameTime, reserved) == 17, "CNA_GameTime.reserved offset");
_Static_assert(sizeof(((CNA_GameTime *)0)->reserved) == 7, "CNA_GameTime.reserved size");

_Static_assert(sizeof(CNA_CallbackError) == 24, "CNA_CallbackError size");
_Static_assert(_Alignof(CNA_CallbackError) == 8, "CNA_CallbackError alignment");
_Static_assert(offsetof(CNA_CallbackError, struct_size) == 0, "CNA_CallbackError.struct_size offset");
_Static_assert(sizeof(((CNA_CallbackError *)0)->struct_size) == 4, "CNA_CallbackError.struct_size size");
_Static_assert(offsetof(CNA_CallbackError, struct_version) == 4, "CNA_CallbackError.struct_version offset");
_Static_assert(sizeof(((CNA_CallbackError *)0)->struct_version) == 4, "CNA_CallbackError.struct_version size");
_Static_assert(offsetof(CNA_CallbackError, message) == 8, "CNA_CallbackError.message offset");
_Static_assert(sizeof(((CNA_CallbackError *)0)->message) == 16, "CNA_CallbackError.message size");

_Static_assert(sizeof(CNA_GameCallbacks) == 56, "CNA_GameCallbacks size");
_Static_assert(_Alignof(CNA_GameCallbacks) == 8, "CNA_GameCallbacks alignment");
_Static_assert(offsetof(CNA_GameCallbacks, struct_size) == 0, "CNA_GameCallbacks.struct_size offset");
_Static_assert(sizeof(((CNA_GameCallbacks *)0)->struct_size) == 4, "CNA_GameCallbacks.struct_size size");
_Static_assert(offsetof(CNA_GameCallbacks, struct_version) == 4, "CNA_GameCallbacks.struct_version offset");
_Static_assert(sizeof(((CNA_GameCallbacks *)0)->struct_version) == 4, "CNA_GameCallbacks.struct_version size");
_Static_assert(offsetof(CNA_GameCallbacks, load_content) == 8, "CNA_GameCallbacks.load_content offset");
_Static_assert(sizeof(((CNA_GameCallbacks *)0)->load_content) == 8, "CNA_GameCallbacks.load_content size");
_Static_assert(offsetof(CNA_GameCallbacks, update) == 16, "CNA_GameCallbacks.update offset");
_Static_assert(sizeof(((CNA_GameCallbacks *)0)->update) == 8, "CNA_GameCallbacks.update size");
_Static_assert(offsetof(CNA_GameCallbacks, draw) == 24, "CNA_GameCallbacks.draw offset");
_Static_assert(sizeof(((CNA_GameCallbacks *)0)->draw) == 8, "CNA_GameCallbacks.draw size");
_Static_assert(offsetof(CNA_GameCallbacks, unload_content) == 32, "CNA_GameCallbacks.unload_content offset");
_Static_assert(sizeof(((CNA_GameCallbacks *)0)->unload_content) == 8, "CNA_GameCallbacks.unload_content size");
_Static_assert(offsetof(CNA_GameCallbacks, exiting) == 40, "CNA_GameCallbacks.exiting offset");
_Static_assert(sizeof(((CNA_GameCallbacks *)0)->exiting) == 8, "CNA_GameCallbacks.exiting size");
_Static_assert(offsetof(CNA_GameCallbacks, context) == 48, "CNA_GameCallbacks.context offset");
_Static_assert(sizeof(((CNA_GameCallbacks *)0)->context) == 8, "CNA_GameCallbacks.context size");

_Static_assert(sizeof(CNA_GameFrameHooks) == 56, "CNA_GameFrameHooks size");
_Static_assert(_Alignof(CNA_GameFrameHooks) == 8, "CNA_GameFrameHooks alignment");
_Static_assert(offsetof(CNA_GameFrameHooks, struct_size) == 0, "CNA_GameFrameHooks.struct_size offset");
_Static_assert(sizeof(((CNA_GameFrameHooks *)0)->struct_size) == 4, "CNA_GameFrameHooks.struct_size size");
_Static_assert(offsetof(CNA_GameFrameHooks, struct_version) == 4, "CNA_GameFrameHooks.struct_version offset");
_Static_assert(sizeof(((CNA_GameFrameHooks *)0)->struct_version) == 4, "CNA_GameFrameHooks.struct_version size");
_Static_assert(offsetof(CNA_GameFrameHooks, initialize) == 8, "CNA_GameFrameHooks.initialize offset");
_Static_assert(sizeof(((CNA_GameFrameHooks *)0)->initialize) == 8, "CNA_GameFrameHooks.initialize size");
_Static_assert(offsetof(CNA_GameFrameHooks, begin_run) == 16, "CNA_GameFrameHooks.begin_run offset");
_Static_assert(sizeof(((CNA_GameFrameHooks *)0)->begin_run) == 8, "CNA_GameFrameHooks.begin_run size");
_Static_assert(offsetof(CNA_GameFrameHooks, end_run) == 24, "CNA_GameFrameHooks.end_run offset");
_Static_assert(sizeof(((CNA_GameFrameHooks *)0)->end_run) == 8, "CNA_GameFrameHooks.end_run size");
_Static_assert(offsetof(CNA_GameFrameHooks, begin_draw) == 32, "CNA_GameFrameHooks.begin_draw offset");
_Static_assert(sizeof(((CNA_GameFrameHooks *)0)->begin_draw) == 8, "CNA_GameFrameHooks.begin_draw size");
_Static_assert(offsetof(CNA_GameFrameHooks, end_draw) == 40, "CNA_GameFrameHooks.end_draw offset");
_Static_assert(sizeof(((CNA_GameFrameHooks *)0)->end_draw) == 8, "CNA_GameFrameHooks.end_draw size");
_Static_assert(offsetof(CNA_GameFrameHooks, context) == 48, "CNA_GameFrameHooks.context offset");
_Static_assert(sizeof(((CNA_GameFrameHooks *)0)->context) == 8, "CNA_GameFrameHooks.context size");

_Static_assert(sizeof(CNA_GameCreateInfo) == 48, "CNA_GameCreateInfo size");
_Static_assert(_Alignof(CNA_GameCreateInfo) == 8, "CNA_GameCreateInfo alignment");
_Static_assert(offsetof(CNA_GameCreateInfo, struct_size) == 0, "CNA_GameCreateInfo.struct_size offset");
_Static_assert(sizeof(((CNA_GameCreateInfo *)0)->struct_size) == 4, "CNA_GameCreateInfo.struct_size size");
_Static_assert(offsetof(CNA_GameCreateInfo, struct_version) == 4, "CNA_GameCreateInfo.struct_version offset");
_Static_assert(sizeof(((CNA_GameCreateInfo *)0)->struct_version) == 4, "CNA_GameCreateInfo.struct_version size");
_Static_assert(offsetof(CNA_GameCreateInfo, is_fixed_time_step) == 8, "CNA_GameCreateInfo.is_fixed_time_step offset");
_Static_assert(sizeof(((CNA_GameCreateInfo *)0)->is_fixed_time_step) == 1, "CNA_GameCreateInfo.is_fixed_time_step size");
_Static_assert(offsetof(CNA_GameCreateInfo, reserved) == 9, "CNA_GameCreateInfo.reserved offset");
_Static_assert(sizeof(((CNA_GameCreateInfo *)0)->reserved) == 7, "CNA_GameCreateInfo.reserved size");
_Static_assert(offsetof(CNA_GameCreateInfo, target_elapsed_time_ticks) == 16, "CNA_GameCreateInfo.target_elapsed_time_ticks offset");
_Static_assert(sizeof(((CNA_GameCreateInfo *)0)->target_elapsed_time_ticks) == 8, "CNA_GameCreateInfo.target_elapsed_time_ticks size");
_Static_assert(offsetof(CNA_GameCreateInfo, window_title) == 24, "CNA_GameCreateInfo.window_title offset");
_Static_assert(sizeof(((CNA_GameCreateInfo *)0)->window_title) == 16, "CNA_GameCreateInfo.window_title size");
_Static_assert(offsetof(CNA_GameCreateInfo, callbacks) == 40, "CNA_GameCreateInfo.callbacks offset");
_Static_assert(sizeof(((CNA_GameCreateInfo *)0)->callbacks) == 8, "CNA_GameCreateInfo.callbacks size");

_Static_assert(sizeof(CNA_TextureInfo) == 16, "CNA_TextureInfo size");
_Static_assert(_Alignof(CNA_TextureInfo) == 4, "CNA_TextureInfo alignment");
_Static_assert(offsetof(CNA_TextureInfo, struct_size) == 0, "CNA_TextureInfo.struct_size offset");
_Static_assert(sizeof(((CNA_TextureInfo *)0)->struct_size) == 4, "CNA_TextureInfo.struct_size size");
_Static_assert(offsetof(CNA_TextureInfo, struct_version) == 4, "CNA_TextureInfo.struct_version offset");
_Static_assert(sizeof(((CNA_TextureInfo *)0)->struct_version) == 4, "CNA_TextureInfo.struct_version size");
_Static_assert(offsetof(CNA_TextureInfo, level_count) == 8, "CNA_TextureInfo.level_count offset");
_Static_assert(sizeof(((CNA_TextureInfo *)0)->level_count) == 4, "CNA_TextureInfo.level_count size");
_Static_assert(offsetof(CNA_TextureInfo, format) == 12, "CNA_TextureInfo.format offset");
_Static_assert(sizeof(((CNA_TextureInfo *)0)->format) == 4, "CNA_TextureInfo.format size");

_Static_assert(sizeof(CNA_Texture2DDecodeInfo) == 24, "CNA_Texture2DDecodeInfo size");
_Static_assert(_Alignof(CNA_Texture2DDecodeInfo) == 4, "CNA_Texture2DDecodeInfo alignment");
_Static_assert(offsetof(CNA_Texture2DDecodeInfo, struct_size) == 0, "CNA_Texture2DDecodeInfo.struct_size offset");
_Static_assert(sizeof(((CNA_Texture2DDecodeInfo *)0)->struct_size) == 4, "CNA_Texture2DDecodeInfo.struct_size size");
_Static_assert(offsetof(CNA_Texture2DDecodeInfo, struct_version) == 4, "CNA_Texture2DDecodeInfo.struct_version offset");
_Static_assert(sizeof(((CNA_Texture2DDecodeInfo *)0)->struct_version) == 4, "CNA_Texture2DDecodeInfo.struct_version size");
_Static_assert(offsetof(CNA_Texture2DDecodeInfo, width) == 8, "CNA_Texture2DDecodeInfo.width offset");
_Static_assert(sizeof(((CNA_Texture2DDecodeInfo *)0)->width) == 4, "CNA_Texture2DDecodeInfo.width size");
_Static_assert(offsetof(CNA_Texture2DDecodeInfo, height) == 12, "CNA_Texture2DDecodeInfo.height offset");
_Static_assert(sizeof(((CNA_Texture2DDecodeInfo *)0)->height) == 4, "CNA_Texture2DDecodeInfo.height size");
_Static_assert(offsetof(CNA_Texture2DDecodeInfo, zoom) == 16, "CNA_Texture2DDecodeInfo.zoom offset");
_Static_assert(sizeof(((CNA_Texture2DDecodeInfo *)0)->zoom) == 1, "CNA_Texture2DDecodeInfo.zoom size");
_Static_assert(offsetof(CNA_Texture2DDecodeInfo, reserved) == 17, "CNA_Texture2DDecodeInfo.reserved offset");
_Static_assert(sizeof(((CNA_Texture2DDecodeInfo *)0)->reserved) == 7, "CNA_Texture2DDecodeInfo.reserved size");

_Static_assert(sizeof(CNA_Texture2DStorageInfo) == 16, "CNA_Texture2DStorageInfo size");
_Static_assert(_Alignof(CNA_Texture2DStorageInfo) == 4, "CNA_Texture2DStorageInfo alignment");
_Static_assert(offsetof(CNA_Texture2DStorageInfo, struct_size) == 0, "CNA_Texture2DStorageInfo.struct_size offset");
_Static_assert(sizeof(((CNA_Texture2DStorageInfo *)0)->struct_size) == 4, "CNA_Texture2DStorageInfo.struct_size size");
_Static_assert(offsetof(CNA_Texture2DStorageInfo, struct_version) == 4, "CNA_Texture2DStorageInfo.struct_version offset");
_Static_assert(sizeof(((CNA_Texture2DStorageInfo *)0)->struct_version) == 4, "CNA_Texture2DStorageInfo.struct_version size");
_Static_assert(offsetof(CNA_Texture2DStorageInfo, has_renderer) == 8, "CNA_Texture2DStorageInfo.has_renderer offset");
_Static_assert(sizeof(((CNA_Texture2DStorageInfo *)0)->has_renderer) == 1, "CNA_Texture2DStorageInfo.has_renderer size");
_Static_assert(offsetof(CNA_Texture2DStorageInfo, has_cpu_shadow) == 9, "CNA_Texture2DStorageInfo.has_cpu_shadow offset");
_Static_assert(sizeof(((CNA_Texture2DStorageInfo *)0)->has_cpu_shadow) == 1, "CNA_Texture2DStorageInfo.has_cpu_shadow size");
_Static_assert(offsetof(CNA_Texture2DStorageInfo, reserved) == 10, "CNA_Texture2DStorageInfo.reserved offset");
_Static_assert(sizeof(((CNA_Texture2DStorageInfo *)0)->reserved) == 6, "CNA_Texture2DStorageInfo.reserved size");

_Static_assert(sizeof(CNA_SpriteBatchBeginInfo) == 16, "CNA_SpriteBatchBeginInfo size");
_Static_assert(_Alignof(CNA_SpriteBatchBeginInfo) == 4, "CNA_SpriteBatchBeginInfo alignment");
_Static_assert(offsetof(CNA_SpriteBatchBeginInfo, struct_size) == 0, "CNA_SpriteBatchBeginInfo.struct_size offset");
_Static_assert(sizeof(((CNA_SpriteBatchBeginInfo *)0)->struct_size) == 4, "CNA_SpriteBatchBeginInfo.struct_size size");
_Static_assert(offsetof(CNA_SpriteBatchBeginInfo, struct_version) == 4, "CNA_SpriteBatchBeginInfo.struct_version offset");
_Static_assert(sizeof(((CNA_SpriteBatchBeginInfo *)0)->struct_version) == 4, "CNA_SpriteBatchBeginInfo.struct_version size");
_Static_assert(offsetof(CNA_SpriteBatchBeginInfo, sort_mode) == 8, "CNA_SpriteBatchBeginInfo.sort_mode offset");
_Static_assert(sizeof(((CNA_SpriteBatchBeginInfo *)0)->sort_mode) == 4, "CNA_SpriteBatchBeginInfo.sort_mode size");
_Static_assert(offsetof(CNA_SpriteBatchBeginInfo, reserved) == 12, "CNA_SpriteBatchBeginInfo.reserved offset");
_Static_assert(sizeof(((CNA_SpriteBatchBeginInfo *)0)->reserved) == 4, "CNA_SpriteBatchBeginInfo.reserved size");

_Static_assert(sizeof(CNA_SpriteCommand) == 72, "CNA_SpriteCommand size");
_Static_assert(_Alignof(CNA_SpriteCommand) == 8, "CNA_SpriteCommand alignment");
_Static_assert(offsetof(CNA_SpriteCommand, struct_size) == 0, "CNA_SpriteCommand.struct_size offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->struct_size) == 4, "CNA_SpriteCommand.struct_size size");
_Static_assert(offsetof(CNA_SpriteCommand, struct_version) == 4, "CNA_SpriteCommand.struct_version offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->struct_version) == 4, "CNA_SpriteCommand.struct_version size");
_Static_assert(offsetof(CNA_SpriteCommand, texture) == 8, "CNA_SpriteCommand.texture offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->texture) == 8, "CNA_SpriteCommand.texture size");
_Static_assert(offsetof(CNA_SpriteCommand, destination) == 16, "CNA_SpriteCommand.destination offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->destination) == 16, "CNA_SpriteCommand.destination size");
_Static_assert(offsetof(CNA_SpriteCommand, source) == 32, "CNA_SpriteCommand.source offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->source) == 16, "CNA_SpriteCommand.source size");
_Static_assert(offsetof(CNA_SpriteCommand, color) == 48, "CNA_SpriteCommand.color offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->color) == 4, "CNA_SpriteCommand.color size");
_Static_assert(offsetof(CNA_SpriteCommand, rotation) == 52, "CNA_SpriteCommand.rotation offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->rotation) == 4, "CNA_SpriteCommand.rotation size");
_Static_assert(offsetof(CNA_SpriteCommand, origin) == 56, "CNA_SpriteCommand.origin offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->origin) == 8, "CNA_SpriteCommand.origin size");
_Static_assert(offsetof(CNA_SpriteCommand, effects) == 64, "CNA_SpriteCommand.effects offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->effects) == 4, "CNA_SpriteCommand.effects size");
_Static_assert(offsetof(CNA_SpriteCommand, layer_depth) == 68, "CNA_SpriteCommand.layer_depth offset");
_Static_assert(sizeof(((CNA_SpriteCommand *)0)->layer_depth) == 4, "CNA_SpriteCommand.layer_depth size");

_Static_assert(sizeof(CNA_KeyboardState) == 40, "CNA_KeyboardState size");
_Static_assert(_Alignof(CNA_KeyboardState) == 8, "CNA_KeyboardState alignment");
_Static_assert(offsetof(CNA_KeyboardState, struct_size) == 0, "CNA_KeyboardState.struct_size offset");
_Static_assert(sizeof(((CNA_KeyboardState *)0)->struct_size) == 4, "CNA_KeyboardState.struct_size size");
_Static_assert(offsetof(CNA_KeyboardState, struct_version) == 4, "CNA_KeyboardState.struct_version offset");
_Static_assert(sizeof(((CNA_KeyboardState *)0)->struct_version) == 4, "CNA_KeyboardState.struct_version size");
_Static_assert(offsetof(CNA_KeyboardState, pressed_key_words) == 8, "CNA_KeyboardState.pressed_key_words offset");
_Static_assert(sizeof(((CNA_KeyboardState *)0)->pressed_key_words) == 32, "CNA_KeyboardState.pressed_key_words size");

_Static_assert(sizeof(CNA_MouseState) == 32, "CNA_MouseState size");
_Static_assert(_Alignof(CNA_MouseState) == 4, "CNA_MouseState alignment");
_Static_assert(offsetof(CNA_MouseState, struct_size) == 0, "CNA_MouseState.struct_size offset");
_Static_assert(sizeof(((CNA_MouseState *)0)->struct_size) == 4, "CNA_MouseState.struct_size size");
_Static_assert(offsetof(CNA_MouseState, struct_version) == 4, "CNA_MouseState.struct_version offset");
_Static_assert(sizeof(((CNA_MouseState *)0)->struct_version) == 4, "CNA_MouseState.struct_version size");
_Static_assert(offsetof(CNA_MouseState, x) == 8, "CNA_MouseState.x offset");
_Static_assert(sizeof(((CNA_MouseState *)0)->x) == 4, "CNA_MouseState.x size");
_Static_assert(offsetof(CNA_MouseState, y) == 12, "CNA_MouseState.y offset");
_Static_assert(sizeof(((CNA_MouseState *)0)->y) == 4, "CNA_MouseState.y size");
_Static_assert(offsetof(CNA_MouseState, scroll_wheel) == 16, "CNA_MouseState.scroll_wheel offset");
_Static_assert(sizeof(((CNA_MouseState *)0)->scroll_wheel) == 4, "CNA_MouseState.scroll_wheel size");
_Static_assert(offsetof(CNA_MouseState, horizontal_scroll_wheel) == 20, "CNA_MouseState.horizontal_scroll_wheel offset");
_Static_assert(sizeof(((CNA_MouseState *)0)->horizontal_scroll_wheel) == 4, "CNA_MouseState.horizontal_scroll_wheel size");
_Static_assert(offsetof(CNA_MouseState, pressed_buttons) == 24, "CNA_MouseState.pressed_buttons offset");
_Static_assert(sizeof(((CNA_MouseState *)0)->pressed_buttons) == 4, "CNA_MouseState.pressed_buttons size");
_Static_assert(offsetof(CNA_MouseState, reserved) == 28, "CNA_MouseState.reserved offset");
_Static_assert(sizeof(((CNA_MouseState *)0)->reserved) == 4, "CNA_MouseState.reserved size");

_Static_assert(sizeof(CNA_GamePadAnalogState) == 24, "CNA_GamePadAnalogState size");
_Static_assert(_Alignof(CNA_GamePadAnalogState) == 4, "CNA_GamePadAnalogState alignment");
_Static_assert(offsetof(CNA_GamePadAnalogState, left_thumb_stick) == 0, "CNA_GamePadAnalogState.left_thumb_stick offset");
_Static_assert(sizeof(((CNA_GamePadAnalogState *)0)->left_thumb_stick) == 8, "CNA_GamePadAnalogState.left_thumb_stick size");
_Static_assert(offsetof(CNA_GamePadAnalogState, right_thumb_stick) == 8, "CNA_GamePadAnalogState.right_thumb_stick offset");
_Static_assert(sizeof(((CNA_GamePadAnalogState *)0)->right_thumb_stick) == 8, "CNA_GamePadAnalogState.right_thumb_stick size");
_Static_assert(offsetof(CNA_GamePadAnalogState, left_trigger) == 16, "CNA_GamePadAnalogState.left_trigger offset");
_Static_assert(sizeof(((CNA_GamePadAnalogState *)0)->left_trigger) == 4, "CNA_GamePadAnalogState.left_trigger size");
_Static_assert(offsetof(CNA_GamePadAnalogState, right_trigger) == 20, "CNA_GamePadAnalogState.right_trigger offset");
_Static_assert(sizeof(((CNA_GamePadAnalogState *)0)->right_trigger) == 4, "CNA_GamePadAnalogState.right_trigger size");

_Static_assert(sizeof(CNA_GamePadState) == 48, "CNA_GamePadState size");
_Static_assert(_Alignof(CNA_GamePadState) == 4, "CNA_GamePadState alignment");
_Static_assert(offsetof(CNA_GamePadState, struct_size) == 0, "CNA_GamePadState.struct_size offset");
_Static_assert(sizeof(((CNA_GamePadState *)0)->struct_size) == 4, "CNA_GamePadState.struct_size size");
_Static_assert(offsetof(CNA_GamePadState, struct_version) == 4, "CNA_GamePadState.struct_version offset");
_Static_assert(sizeof(((CNA_GamePadState *)0)->struct_version) == 4, "CNA_GamePadState.struct_version size");
_Static_assert(offsetof(CNA_GamePadState, is_connected) == 8, "CNA_GamePadState.is_connected offset");
_Static_assert(sizeof(((CNA_GamePadState *)0)->is_connected) == 1, "CNA_GamePadState.is_connected size");
_Static_assert(offsetof(CNA_GamePadState, reserved0) == 9, "CNA_GamePadState.reserved0 offset");
_Static_assert(sizeof(((CNA_GamePadState *)0)->reserved0) == 3, "CNA_GamePadState.reserved0 size");
_Static_assert(offsetof(CNA_GamePadState, packet_number) == 12, "CNA_GamePadState.packet_number offset");
_Static_assert(sizeof(((CNA_GamePadState *)0)->packet_number) == 4, "CNA_GamePadState.packet_number size");
_Static_assert(offsetof(CNA_GamePadState, pressed_buttons) == 16, "CNA_GamePadState.pressed_buttons offset");
_Static_assert(sizeof(((CNA_GamePadState *)0)->pressed_buttons) == 4, "CNA_GamePadState.pressed_buttons size");
_Static_assert(offsetof(CNA_GamePadState, reserved1) == 20, "CNA_GamePadState.reserved1 offset");
_Static_assert(sizeof(((CNA_GamePadState *)0)->reserved1) == 4, "CNA_GamePadState.reserved1 size");
_Static_assert(offsetof(CNA_GamePadState, analog) == 24, "CNA_GamePadState.analog offset");
_Static_assert(sizeof(((CNA_GamePadState *)0)->analog) == 24, "CNA_GamePadState.analog size");

_Static_assert(sizeof(CNA_GamePadCapabilities) == 48, "CNA_GamePadCapabilities size");
_Static_assert(_Alignof(CNA_GamePadCapabilities) == 4, "CNA_GamePadCapabilities alignment");
_Static_assert(offsetof(CNA_GamePadCapabilities, struct_size) == 0, "CNA_GamePadCapabilities.struct_size offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->struct_size) == 4, "CNA_GamePadCapabilities.struct_size size");
_Static_assert(offsetof(CNA_GamePadCapabilities, struct_version) == 4, "CNA_GamePadCapabilities.struct_version offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->struct_version) == 4, "CNA_GamePadCapabilities.struct_version size");
_Static_assert(offsetof(CNA_GamePadCapabilities, gamepad_type) == 8, "CNA_GamePadCapabilities.gamepad_type offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->gamepad_type) == 4, "CNA_GamePadCapabilities.gamepad_type size");
_Static_assert(offsetof(CNA_GamePadCapabilities, is_connected) == 12, "CNA_GamePadCapabilities.is_connected offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->is_connected) == 1, "CNA_GamePadCapabilities.is_connected size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_a_button) == 13, "CNA_GamePadCapabilities.has_a_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_a_button) == 1, "CNA_GamePadCapabilities.has_a_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_b_button) == 14, "CNA_GamePadCapabilities.has_b_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_b_button) == 1, "CNA_GamePadCapabilities.has_b_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_x_button) == 15, "CNA_GamePadCapabilities.has_x_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_x_button) == 1, "CNA_GamePadCapabilities.has_x_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_y_button) == 16, "CNA_GamePadCapabilities.has_y_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_y_button) == 1, "CNA_GamePadCapabilities.has_y_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_back_button) == 17, "CNA_GamePadCapabilities.has_back_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_back_button) == 1, "CNA_GamePadCapabilities.has_back_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_start_button) == 18, "CNA_GamePadCapabilities.has_start_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_start_button) == 1, "CNA_GamePadCapabilities.has_start_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_big_button) == 19, "CNA_GamePadCapabilities.has_big_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_big_button) == 1, "CNA_GamePadCapabilities.has_big_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_dpad_up_button) == 20, "CNA_GamePadCapabilities.has_dpad_up_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_dpad_up_button) == 1, "CNA_GamePadCapabilities.has_dpad_up_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_dpad_down_button) == 21, "CNA_GamePadCapabilities.has_dpad_down_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_dpad_down_button) == 1, "CNA_GamePadCapabilities.has_dpad_down_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_dpad_left_button) == 22, "CNA_GamePadCapabilities.has_dpad_left_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_dpad_left_button) == 1, "CNA_GamePadCapabilities.has_dpad_left_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_dpad_right_button) == 23, "CNA_GamePadCapabilities.has_dpad_right_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_dpad_right_button) == 1, "CNA_GamePadCapabilities.has_dpad_right_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_left_shoulder_button) == 24, "CNA_GamePadCapabilities.has_left_shoulder_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_left_shoulder_button) == 1, "CNA_GamePadCapabilities.has_left_shoulder_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_right_shoulder_button) == 25, "CNA_GamePadCapabilities.has_right_shoulder_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_right_shoulder_button) == 1, "CNA_GamePadCapabilities.has_right_shoulder_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_left_stick_button) == 26, "CNA_GamePadCapabilities.has_left_stick_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_left_stick_button) == 1, "CNA_GamePadCapabilities.has_left_stick_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_right_stick_button) == 27, "CNA_GamePadCapabilities.has_right_stick_button offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_right_stick_button) == 1, "CNA_GamePadCapabilities.has_right_stick_button size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_left_x_thumb_stick) == 28, "CNA_GamePadCapabilities.has_left_x_thumb_stick offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_left_x_thumb_stick) == 1, "CNA_GamePadCapabilities.has_left_x_thumb_stick size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_left_y_thumb_stick) == 29, "CNA_GamePadCapabilities.has_left_y_thumb_stick offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_left_y_thumb_stick) == 1, "CNA_GamePadCapabilities.has_left_y_thumb_stick size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_right_x_thumb_stick) == 30, "CNA_GamePadCapabilities.has_right_x_thumb_stick offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_right_x_thumb_stick) == 1, "CNA_GamePadCapabilities.has_right_x_thumb_stick size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_right_y_thumb_stick) == 31, "CNA_GamePadCapabilities.has_right_y_thumb_stick offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_right_y_thumb_stick) == 1, "CNA_GamePadCapabilities.has_right_y_thumb_stick size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_left_trigger) == 32, "CNA_GamePadCapabilities.has_left_trigger offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_left_trigger) == 1, "CNA_GamePadCapabilities.has_left_trigger size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_right_trigger) == 33, "CNA_GamePadCapabilities.has_right_trigger offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_right_trigger) == 1, "CNA_GamePadCapabilities.has_right_trigger size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_left_vibration_motor) == 34, "CNA_GamePadCapabilities.has_left_vibration_motor offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_left_vibration_motor) == 1, "CNA_GamePadCapabilities.has_left_vibration_motor size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_right_vibration_motor) == 35, "CNA_GamePadCapabilities.has_right_vibration_motor offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_right_vibration_motor) == 1, "CNA_GamePadCapabilities.has_right_vibration_motor size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_voice_support) == 36, "CNA_GamePadCapabilities.has_voice_support offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_voice_support) == 1, "CNA_GamePadCapabilities.has_voice_support size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_light_bar_ext) == 37, "CNA_GamePadCapabilities.has_light_bar_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_light_bar_ext) == 1, "CNA_GamePadCapabilities.has_light_bar_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_trigger_vibration_motors_ext) == 38, "CNA_GamePadCapabilities.has_trigger_vibration_motors_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_trigger_vibration_motors_ext) == 1, "CNA_GamePadCapabilities.has_trigger_vibration_motors_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_misc1_ext) == 39, "CNA_GamePadCapabilities.has_misc1_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_misc1_ext) == 1, "CNA_GamePadCapabilities.has_misc1_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_paddle1_ext) == 40, "CNA_GamePadCapabilities.has_paddle1_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_paddle1_ext) == 1, "CNA_GamePadCapabilities.has_paddle1_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_paddle2_ext) == 41, "CNA_GamePadCapabilities.has_paddle2_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_paddle2_ext) == 1, "CNA_GamePadCapabilities.has_paddle2_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_paddle3_ext) == 42, "CNA_GamePadCapabilities.has_paddle3_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_paddle3_ext) == 1, "CNA_GamePadCapabilities.has_paddle3_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_paddle4_ext) == 43, "CNA_GamePadCapabilities.has_paddle4_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_paddle4_ext) == 1, "CNA_GamePadCapabilities.has_paddle4_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_touchpad_ext) == 44, "CNA_GamePadCapabilities.has_touchpad_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_touchpad_ext) == 1, "CNA_GamePadCapabilities.has_touchpad_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_gyro_ext) == 45, "CNA_GamePadCapabilities.has_gyro_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_gyro_ext) == 1, "CNA_GamePadCapabilities.has_gyro_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, has_accelerometer_ext) == 46, "CNA_GamePadCapabilities.has_accelerometer_ext offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->has_accelerometer_ext) == 1, "CNA_GamePadCapabilities.has_accelerometer_ext size");
_Static_assert(offsetof(CNA_GamePadCapabilities, reserved) == 47, "CNA_GamePadCapabilities.reserved offset");
_Static_assert(sizeof(((CNA_GamePadCapabilities *)0)->reserved) == 1, "CNA_GamePadCapabilities.reserved size");

_Static_assert(sizeof(CNA_RendererInfo) == 32, "CNA_RendererInfo size");
_Static_assert(_Alignof(CNA_RendererInfo) == 8, "CNA_RendererInfo alignment");
_Static_assert(offsetof(CNA_RendererInfo, struct_size) == 0, "CNA_RendererInfo.struct_size offset");
_Static_assert(sizeof(((CNA_RendererInfo *)0)->struct_size) == 4, "CNA_RendererInfo.struct_size size");
_Static_assert(offsetof(CNA_RendererInfo, struct_version) == 4, "CNA_RendererInfo.struct_version offset");
_Static_assert(sizeof(((CNA_RendererInfo *)0)->struct_version) == 4, "CNA_RendererInfo.struct_version size");
_Static_assert(offsetof(CNA_RendererInfo, renderer_name_byte_length) == 8, "CNA_RendererInfo.renderer_name_byte_length offset");
_Static_assert(sizeof(((CNA_RendererInfo *)0)->renderer_name_byte_length) == 8, "CNA_RendererInfo.renderer_name_byte_length size");
_Static_assert(offsetof(CNA_RendererInfo, capability_flags) == 16, "CNA_RendererInfo.capability_flags offset");
_Static_assert(sizeof(((CNA_RendererInfo *)0)->capability_flags) == 8, "CNA_RendererInfo.capability_flags size");
_Static_assert(offsetof(CNA_RendererInfo, renderer_type) == 24, "CNA_RendererInfo.renderer_type offset");
_Static_assert(sizeof(((CNA_RendererInfo *)0)->renderer_type) == 4, "CNA_RendererInfo.renderer_type size");
_Static_assert(offsetof(CNA_RendererInfo, max_texture_dimension) == 28, "CNA_RendererInfo.max_texture_dimension offset");
_Static_assert(sizeof(((CNA_RendererInfo *)0)->max_texture_dimension) == 4, "CNA_RendererInfo.max_texture_dimension size");

_Static_assert(sizeof(CNA_SpriteScaledCommand) == 72, "CNA_SpriteScaledCommand size");
_Static_assert(_Alignof(CNA_SpriteScaledCommand) == 8, "CNA_SpriteScaledCommand alignment");
_Static_assert(offsetof(CNA_SpriteScaledCommand, struct_size) == 0, "CNA_SpriteScaledCommand.struct_size offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->struct_size) == 4, "CNA_SpriteScaledCommand.struct_size size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, struct_version) == 4, "CNA_SpriteScaledCommand.struct_version offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->struct_version) == 4, "CNA_SpriteScaledCommand.struct_version size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, texture) == 8, "CNA_SpriteScaledCommand.texture offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->texture) == 8, "CNA_SpriteScaledCommand.texture size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, position) == 16, "CNA_SpriteScaledCommand.position offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->position) == 8, "CNA_SpriteScaledCommand.position size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, source) == 24, "CNA_SpriteScaledCommand.source offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->source) == 16, "CNA_SpriteScaledCommand.source size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, color) == 40, "CNA_SpriteScaledCommand.color offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->color) == 4, "CNA_SpriteScaledCommand.color size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, rotation) == 44, "CNA_SpriteScaledCommand.rotation offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->rotation) == 4, "CNA_SpriteScaledCommand.rotation size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, origin) == 48, "CNA_SpriteScaledCommand.origin offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->origin) == 8, "CNA_SpriteScaledCommand.origin size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, scale) == 56, "CNA_SpriteScaledCommand.scale offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->scale) == 8, "CNA_SpriteScaledCommand.scale size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, effects) == 64, "CNA_SpriteScaledCommand.effects offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->effects) == 4, "CNA_SpriteScaledCommand.effects size");
_Static_assert(offsetof(CNA_SpriteScaledCommand, layer_depth) == 68, "CNA_SpriteScaledCommand.layer_depth offset");
_Static_assert(sizeof(((CNA_SpriteScaledCommand *)0)->layer_depth) == 4, "CNA_SpriteScaledCommand.layer_depth size");

/* --- prototypes: assigning each route to its declared type is a compile
   error unless the declaration matches exactly --- */
uint32_t (*const cna_lisp_probe_cna_get_abi_version)(void) = cna_get_abi_version;
CNA_Result (*const cna_lisp_probe_cna_error_get_last_info)(CNA_ErrorInfo*) = cna_error_get_last_info;
CNA_Result (*const cna_lisp_probe_cna_error_get_last_message_size)(uint64_t*) = cna_error_get_last_message_size;
CNA_Result (*const cna_lisp_probe_cna_error_copy_last_message)(char*, uint64_t, uint64_t*) = cna_error_copy_last_message;
CNA_Result (*const cna_lisp_probe_cna_game_create)(const CNA_GameCreateInfo*, CNA_Handle*) = cna_game_create;
CNA_Result (*const cna_lisp_probe_cna_game_destroy)(CNA_Handle) = cna_game_destroy;
CNA_Result (*const cna_lisp_probe_cna_game_run)(CNA_Handle) = cna_game_run;
CNA_Result (*const cna_lisp_probe_cna_game_run_one_frame)(CNA_Handle) = cna_game_run_one_frame;
CNA_Result (*const cna_lisp_probe_cna_game_tick)(CNA_Handle) = cna_game_tick;
CNA_Result (*const cna_lisp_probe_cna_game_request_exit)(CNA_Handle) = cna_game_request_exit;
CNA_Result (*const cna_lisp_probe_cna_game_suppress_draw)(CNA_Handle) = cna_game_suppress_draw;
CNA_Result (*const cna_lisp_probe_cna_game_reset_elapsed_time)(CNA_Handle) = cna_game_reset_elapsed_time;
CNA_Result (*const cna_lisp_probe_cna_game_clear)(CNA_Handle, CNA_Color) = cna_game_clear;
CNA_Result (*const cna_lisp_probe_cna_game_set_window_title)(CNA_Handle, CNA_StringView) = cna_game_set_window_title;
CNA_Result (*const cna_lisp_probe_cna_game_set_frame_hooks_ext)(CNA_Handle, const CNA_GameFrameHooks*) = cna_game_set_frame_hooks_ext;
CNA_Result (*const cna_lisp_probe_cna_game_get_is_active)(CNA_Handle, CNA_Bool*) = cna_game_get_is_active;
CNA_Result (*const cna_lisp_probe_cna_game_get_is_mouse_visible)(CNA_Handle, CNA_Bool*) = cna_game_get_is_mouse_visible;
CNA_Result (*const cna_lisp_probe_cna_game_set_is_mouse_visible)(CNA_Handle, CNA_Bool) = cna_game_set_is_mouse_visible;
CNA_Result (*const cna_lisp_probe_cna_game_get_is_fixed_time_step)(CNA_Handle, CNA_Bool*) = cna_game_get_is_fixed_time_step;
CNA_Result (*const cna_lisp_probe_cna_game_set_is_fixed_time_step)(CNA_Handle, CNA_Bool) = cna_game_set_is_fixed_time_step;
CNA_Result (*const cna_lisp_probe_cna_game_get_target_elapsed_time_ticks)(CNA_Handle, int64_t*) = cna_game_get_target_elapsed_time_ticks;
CNA_Result (*const cna_lisp_probe_cna_game_set_target_elapsed_time_ticks)(CNA_Handle, int64_t) = cna_game_set_target_elapsed_time_ticks;
CNA_Result (*const cna_lisp_probe_cna_game_get_inactive_sleep_time_ticks)(CNA_Handle, int64_t*) = cna_game_get_inactive_sleep_time_ticks;
CNA_Result (*const cna_lisp_probe_cna_game_set_inactive_sleep_time_ticks)(CNA_Handle, int64_t) = cna_game_set_inactive_sleep_time_ticks;
CNA_Result (*const cna_lisp_probe_cna_game_get_type_name_size)(CNA_Handle, uint64_t*) = cna_game_get_type_name_size;
CNA_Result (*const cna_lisp_probe_cna_game_copy_type_name)(CNA_Handle, char*, uint64_t, uint64_t*) = cna_game_copy_type_name;
CNA_Result (*const cna_lisp_probe_cna_game_get_graphics_device)(CNA_Handle, CNA_Handle*) = cna_game_get_graphics_device;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_get_viewport)(CNA_Handle, CNA_Viewport*) = cna_graphics_device_get_viewport;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_clear_rgba)(CNA_Handle, float, float, float, float) = cna_graphics_device_clear_rgba;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_present)(CNA_Handle) = cna_graphics_device_present;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_get_renderer_info)(CNA_Handle, CNA_RendererInfo*) = cna_graphics_device_get_renderer_info;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_copy_renderer_name)(CNA_Handle, char*, uint64_t, uint64_t*) = cna_graphics_device_copy_renderer_name;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_get_type_name_size)(CNA_Handle, uint64_t*) = cna_graphics_device_get_type_name_size;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_copy_type_name)(CNA_Handle, char*, uint64_t, uint64_t*) = cna_graphics_device_copy_type_name;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_create)(CNA_Handle, CNA_GraphicsDeviceManagerHandle*) = cna_graphics_device_manager_create;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_destroy)(CNA_GraphicsDeviceManagerHandle) = cna_graphics_device_manager_destroy;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_apply_changes)(CNA_GraphicsDeviceManagerHandle) = cna_graphics_device_manager_apply_changes;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_toggle_full_screen)(CNA_GraphicsDeviceManagerHandle) = cna_graphics_device_manager_toggle_full_screen;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_get_is_full_screen)(CNA_GraphicsDeviceManagerHandle, CNA_Bool*) = cna_graphics_device_manager_get_is_full_screen;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_set_is_full_screen)(CNA_GraphicsDeviceManagerHandle, CNA_Bool) = cna_graphics_device_manager_set_is_full_screen;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_get_preferred_back_buffer_width)(CNA_GraphicsDeviceManagerHandle, int32_t*) = cna_graphics_device_manager_get_preferred_back_buffer_width;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_set_preferred_back_buffer_width)(CNA_GraphicsDeviceManagerHandle, int32_t) = cna_graphics_device_manager_set_preferred_back_buffer_width;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_get_preferred_back_buffer_height)(CNA_GraphicsDeviceManagerHandle, int32_t*) = cna_graphics_device_manager_get_preferred_back_buffer_height;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_set_preferred_back_buffer_height)(CNA_GraphicsDeviceManagerHandle, int32_t) = cna_graphics_device_manager_set_preferred_back_buffer_height;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_get_synchronize_with_vertical_retrace)(CNA_GraphicsDeviceManagerHandle, CNA_Bool*) = cna_graphics_device_manager_get_synchronize_with_vertical_retrace;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_set_synchronize_with_vertical_retrace)(CNA_GraphicsDeviceManagerHandle, CNA_Bool) = cna_graphics_device_manager_set_synchronize_with_vertical_retrace;
CNA_Result (*const cna_lisp_probe_cna_graphics_device_manager_get_graphics_device)(CNA_GraphicsDeviceManagerHandle, CNA_Handle*) = cna_graphics_device_manager_get_graphics_device;
CNA_Result (*const cna_lisp_probe_cna_texture2d_create_from_encoded_memory)(CNA_Handle, const uint8_t*, uint64_t, const CNA_Texture2DDecodeInfo*, CNA_Handle*) = cna_texture2d_create_from_encoded_memory;
CNA_Result (*const cna_lisp_probe_cna_texture2d_create_from_file_with_device)(CNA_Handle, CNA_StringView, CNA_Handle*) = cna_texture2d_create_from_file_with_device;
CNA_Result (*const cna_lisp_probe_cna_texture2d_destroy)(CNA_Handle) = cna_texture2d_destroy;
CNA_Result (*const cna_lisp_probe_cna_texture2d_get_storage_info)(CNA_Handle, CNA_Texture2DStorageInfo*) = cna_texture2d_get_storage_info;
CNA_Result (*const cna_lisp_probe_cna_texture2d_get_type_name_byte_count)(CNA_Handle, uint64_t*) = cna_texture2d_get_type_name_byte_count;
CNA_Result (*const cna_lisp_probe_cna_texture2d_copy_type_name)(CNA_Handle, char*, uint64_t, uint64_t*) = cna_texture2d_copy_type_name;
CNA_Result (*const cna_lisp_probe_cna_texture_get_info)(CNA_Handle, CNA_TextureInfo*) = cna_texture_get_info;
CNA_Result (*const cna_lisp_probe_cna_sprite_batch_create)(CNA_Handle, CNA_Handle*) = cna_sprite_batch_create;
CNA_Result (*const cna_lisp_probe_cna_sprite_batch_destroy)(CNA_Handle) = cna_sprite_batch_destroy;
CNA_Result (*const cna_lisp_probe_cna_sprite_batch_begin)(CNA_Handle, const CNA_SpriteBatchBeginInfo*) = cna_sprite_batch_begin;
CNA_Result (*const cna_lisp_probe_cna_sprite_batch_submit_many)(CNA_Handle, const CNA_SpriteCommand*, uint64_t) = cna_sprite_batch_submit_many;
CNA_Result (*const cna_lisp_probe_cna_sprite_batch_submit_scaled_many)(CNA_Handle, const CNA_SpriteScaledCommand*, uint64_t) = cna_sprite_batch_submit_scaled_many;
CNA_Result (*const cna_lisp_probe_cna_sprite_batch_end)(CNA_Handle) = cna_sprite_batch_end;
CNA_Result (*const cna_lisp_probe_cna_sprite_batch_get_type_name_size)(CNA_Handle, uint64_t*) = cna_sprite_batch_get_type_name_size;
CNA_Result (*const cna_lisp_probe_cna_sprite_batch_copy_type_name)(CNA_Handle, char*, uint64_t, uint64_t*) = cna_sprite_batch_copy_type_name;
CNA_Result (*const cna_lisp_probe_cna_keyboard_get_state)(CNA_Handle, CNA_KeyboardState*) = cna_keyboard_get_state;
CNA_Result (*const cna_lisp_probe_cna_keyboard_get_state_for_player)(CNA_Handle, CNA_PlayerIndex, CNA_KeyboardState*) = cna_keyboard_get_state_for_player;
CNA_Result (*const cna_lisp_probe_cna_keyboard_state_init)(CNA_KeyboardState*) = cna_keyboard_state_init;
CNA_Result (*const cna_lisp_probe_cna_keyboard_state_init_from_keys)(const CNA_Key*, uint64_t, CNA_KeyboardState*) = cna_keyboard_state_init_from_keys;
CNA_Result (*const cna_lisp_probe_cna_keyboard_state_get_key_state)(const CNA_KeyboardState*, CNA_Key, CNA_KeyState*) = cna_keyboard_state_get_key_state;
CNA_Result (*const cna_lisp_probe_cna_keyboard_state_equals)(const CNA_KeyboardState*, const CNA_KeyboardState*, CNA_Bool*) = cna_keyboard_state_equals;
CNA_Result (*const cna_lisp_probe_cna_keyboard_state_get_hash_code)(const CNA_KeyboardState*, int32_t*) = cna_keyboard_state_get_hash_code;
CNA_Result (*const cna_lisp_probe_cna_mouse_get_state)(CNA_Handle, CNA_MouseState*) = cna_mouse_get_state;
CNA_Result (*const cna_lisp_probe_cna_mouse_set_position)(CNA_Handle, int32_t, int32_t) = cna_mouse_set_position;
CNA_Result (*const cna_lisp_probe_cna_mouse_state_init)(CNA_MouseState*) = cna_mouse_state_init;
CNA_Result (*const cna_lisp_probe_cna_mouse_state_init_from_values)(int32_t, int32_t, int32_t, CNA_MouseButtonFlags, CNA_MouseState*) = cna_mouse_state_init_from_values;
CNA_Result (*const cna_lisp_probe_cna_mouse_state_equals)(const CNA_MouseState*, const CNA_MouseState*, CNA_Bool*) = cna_mouse_state_equals;
CNA_Result (*const cna_lisp_probe_cna_gamepad_get_state)(CNA_Handle, CNA_PlayerIndex, CNA_GamePadState*) = cna_gamepad_get_state;
CNA_Result (*const cna_lisp_probe_cna_gamepad_get_state_with_dead_zone)(CNA_Handle, CNA_PlayerIndex, CNA_GamePadDeadZone, CNA_GamePadState*) = cna_gamepad_get_state_with_dead_zone;
CNA_Result (*const cna_lisp_probe_cna_gamepad_get_capabilities)(CNA_Handle, CNA_PlayerIndex, CNA_GamePadCapabilities*) = cna_gamepad_get_capabilities;
CNA_Result (*const cna_lisp_probe_cna_gamepad_set_vibration)(CNA_Handle, CNA_PlayerIndex, float, float, CNA_Bool*) = cna_gamepad_set_vibration;

/* --- callbacks --- */
_Static_assert(sizeof(CNA_GameLifecycleCallback) == sizeof(void (*)(void)), "CNA_GameLifecycleCallback size");
_Static_assert(sizeof(CNA_GameBeginDrawCallback) == sizeof(void (*)(void)), "CNA_GameBeginDrawCallback size");

/* --- constants --- */
_Static_assert((int64_t)(CNA_ABI_VERSION) == INT64_C(5376), "CNA_ABI_VERSION value");
_Static_assert((int64_t)(CNA_ABI_VERSION_MAJOR) == INT64_C(0), "CNA_ABI_VERSION_MAJOR value");
_Static_assert((int64_t)(CNA_ABI_VERSION_MINOR) == INT64_C(21), "CNA_ABI_VERSION_MINOR value");
_Static_assert((int64_t)(CNA_ABI_VERSION_PATCH) == INT64_C(0), "CNA_ABI_VERSION_PATCH value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_ARGUMENT) == INT64_C(1), "CNA_ERROR_CATEGORY_ARGUMENT value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_CALLBACK) == INT64_C(9), "CNA_ERROR_CATEGORY_CALLBACK value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_ENCODING) == INT64_C(11), "CNA_ERROR_CATEGORY_ENCODING value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_HANDLE) == INT64_C(2), "CNA_ERROR_CATEGORY_HANDLE value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_INTERNAL) == INT64_C(12), "CNA_ERROR_CATEGORY_INTERNAL value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_IO) == INT64_C(5), "CNA_ERROR_CATEGORY_IO value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_MEMORY) == INT64_C(4), "CNA_ERROR_CATEGORY_MEMORY value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_NONE) == INT64_C(0), "CNA_ERROR_CATEGORY_NONE value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_NOT_SUPPORTED) == INT64_C(6), "CNA_ERROR_CATEGORY_NOT_SUPPORTED value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_PLATFORM) == INT64_C(7), "CNA_ERROR_CATEGORY_PLATFORM value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_RANGE) == INT64_C(10), "CNA_ERROR_CATEGORY_RANGE value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_SHUTTING_DOWN) == INT64_C(13), "CNA_ERROR_CATEGORY_SHUTTING_DOWN value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_STATE) == INT64_C(3), "CNA_ERROR_CATEGORY_STATE value");
_Static_assert((int64_t)(CNA_ERROR_CATEGORY_THREAD) == INT64_C(8), "CNA_ERROR_CATEGORY_THREAD value");
_Static_assert((int64_t)(CNA_FALSE) == INT64_C(0), "CNA_FALSE value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_A) == INT64_C(4096), "CNA_GAMEPAD_BUTTON_A value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_B) == INT64_C(8192), "CNA_GAMEPAD_BUTTON_B value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_BACK) == INT64_C(32), "CNA_GAMEPAD_BUTTON_BACK value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_BIG_BUTTON) == INT64_C(2048), "CNA_GAMEPAD_BUTTON_BIG_BUTTON value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_DPAD_DOWN) == INT64_C(2), "CNA_GAMEPAD_BUTTON_DPAD_DOWN value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_DPAD_LEFT) == INT64_C(4), "CNA_GAMEPAD_BUTTON_DPAD_LEFT value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_DPAD_RIGHT) == INT64_C(8), "CNA_GAMEPAD_BUTTON_DPAD_RIGHT value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_DPAD_UP) == INT64_C(1), "CNA_GAMEPAD_BUTTON_DPAD_UP value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_LEFT_SHOULDER) == INT64_C(256), "CNA_GAMEPAD_BUTTON_LEFT_SHOULDER value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_LEFT_STICK) == INT64_C(64), "CNA_GAMEPAD_BUTTON_LEFT_STICK value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_DOWN) == INT64_C(536870912), "CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_DOWN value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_LEFT) == INT64_C(2097152), "CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_LEFT value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_RIGHT) == INT64_C(1073741824), "CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_RIGHT value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_UP) == INT64_C(268435456), "CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_UP value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_LEFT_TRIGGER) == INT64_C(8388608), "CNA_GAMEPAD_BUTTON_LEFT_TRIGGER value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_NONE) == INT64_C(0), "CNA_GAMEPAD_BUTTON_NONE value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_RIGHT_SHOULDER) == INT64_C(512), "CNA_GAMEPAD_BUTTON_RIGHT_SHOULDER value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_RIGHT_STICK) == INT64_C(128), "CNA_GAMEPAD_BUTTON_RIGHT_STICK value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_DOWN) == INT64_C(33554432), "CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_DOWN value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_LEFT) == INT64_C(134217728), "CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_LEFT value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_RIGHT) == INT64_C(67108864), "CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_RIGHT value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_UP) == INT64_C(16777216), "CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_UP value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_RIGHT_TRIGGER) == INT64_C(4194304), "CNA_GAMEPAD_BUTTON_RIGHT_TRIGGER value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_START) == INT64_C(16), "CNA_GAMEPAD_BUTTON_START value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_X) == INT64_C(16384), "CNA_GAMEPAD_BUTTON_X value");
_Static_assert((int64_t)(CNA_GAMEPAD_BUTTON_Y) == INT64_C(32768), "CNA_GAMEPAD_BUTTON_Y value");
_Static_assert((int64_t)(CNA_GAMEPAD_DEAD_ZONE_CIRCULAR) == INT64_C(2), "CNA_GAMEPAD_DEAD_ZONE_CIRCULAR value");
_Static_assert((int64_t)(CNA_GAMEPAD_DEAD_ZONE_INDEPENDENT_AXES) == INT64_C(1), "CNA_GAMEPAD_DEAD_ZONE_INDEPENDENT_AXES value");
_Static_assert((int64_t)(CNA_GAMEPAD_DEAD_ZONE_NONE) == INT64_C(0), "CNA_GAMEPAD_DEAD_ZONE_NONE value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_ALTERNATE_GUITAR) == INT64_C(7), "CNA_GAMEPAD_TYPE_ALTERNATE_GUITAR value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_ARCADE_STICK) == INT64_C(3), "CNA_GAMEPAD_TYPE_ARCADE_STICK value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_BIG_BUTTON_PAD) == INT64_C(9), "CNA_GAMEPAD_TYPE_BIG_BUTTON_PAD value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_DANCE_PAD) == INT64_C(5), "CNA_GAMEPAD_TYPE_DANCE_PAD value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_DRUM_KIT) == INT64_C(8), "CNA_GAMEPAD_TYPE_DRUM_KIT value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_FLIGHT_STICK) == INT64_C(4), "CNA_GAMEPAD_TYPE_FLIGHT_STICK value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_GAMEPAD) == INT64_C(1), "CNA_GAMEPAD_TYPE_GAMEPAD value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_GUITAR) == INT64_C(6), "CNA_GAMEPAD_TYPE_GUITAR value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_UNKNOWN) == INT64_C(0), "CNA_GAMEPAD_TYPE_UNKNOWN value");
_Static_assert((int64_t)(CNA_GAMEPAD_TYPE_WHEEL) == INT64_C(2), "CNA_GAMEPAD_TYPE_WHEEL value");
_Static_assert((int64_t)(CNA_INVALID_HANDLE) == INT64_C(0), "CNA_INVALID_HANDLE value");
_Static_assert((int64_t)(CNA_KEY_A) == INT64_C(65), "CNA_KEY_A value");
_Static_assert((int64_t)(CNA_KEY_ADD) == INT64_C(107), "CNA_KEY_ADD value");
_Static_assert((int64_t)(CNA_KEY_APPS) == INT64_C(93), "CNA_KEY_APPS value");
_Static_assert((int64_t)(CNA_KEY_ATTN) == INT64_C(246), "CNA_KEY_ATTN value");
_Static_assert((int64_t)(CNA_KEY_B) == INT64_C(66), "CNA_KEY_B value");
_Static_assert((int64_t)(CNA_KEY_BACK) == INT64_C(8), "CNA_KEY_BACK value");
_Static_assert((int64_t)(CNA_KEY_BROWSER_BACK) == INT64_C(166), "CNA_KEY_BROWSER_BACK value");
_Static_assert((int64_t)(CNA_KEY_BROWSER_FAVORITES) == INT64_C(171), "CNA_KEY_BROWSER_FAVORITES value");
_Static_assert((int64_t)(CNA_KEY_BROWSER_FORWARD) == INT64_C(167), "CNA_KEY_BROWSER_FORWARD value");
_Static_assert((int64_t)(CNA_KEY_BROWSER_HOME) == INT64_C(172), "CNA_KEY_BROWSER_HOME value");
_Static_assert((int64_t)(CNA_KEY_BROWSER_REFRESH) == INT64_C(168), "CNA_KEY_BROWSER_REFRESH value");
_Static_assert((int64_t)(CNA_KEY_BROWSER_SEARCH) == INT64_C(170), "CNA_KEY_BROWSER_SEARCH value");
_Static_assert((int64_t)(CNA_KEY_BROWSER_STOP) == INT64_C(169), "CNA_KEY_BROWSER_STOP value");
_Static_assert((int64_t)(CNA_KEY_C) == INT64_C(67), "CNA_KEY_C value");
_Static_assert((int64_t)(CNA_KEY_CAPS_LOCK) == INT64_C(20), "CNA_KEY_CAPS_LOCK value");
_Static_assert((int64_t)(CNA_KEY_CHAT_PAD_GREEN) == INT64_C(202), "CNA_KEY_CHAT_PAD_GREEN value");
_Static_assert((int64_t)(CNA_KEY_CHAT_PAD_ORANGE) == INT64_C(203), "CNA_KEY_CHAT_PAD_ORANGE value");
_Static_assert((int64_t)(CNA_KEY_CRSEL) == INT64_C(247), "CNA_KEY_CRSEL value");
_Static_assert((int64_t)(CNA_KEY_D) == INT64_C(68), "CNA_KEY_D value");
_Static_assert((int64_t)(CNA_KEY_D0) == INT64_C(48), "CNA_KEY_D0 value");
_Static_assert((int64_t)(CNA_KEY_D1) == INT64_C(49), "CNA_KEY_D1 value");
_Static_assert((int64_t)(CNA_KEY_D2) == INT64_C(50), "CNA_KEY_D2 value");
_Static_assert((int64_t)(CNA_KEY_D3) == INT64_C(51), "CNA_KEY_D3 value");
_Static_assert((int64_t)(CNA_KEY_D4) == INT64_C(52), "CNA_KEY_D4 value");
_Static_assert((int64_t)(CNA_KEY_D5) == INT64_C(53), "CNA_KEY_D5 value");
_Static_assert((int64_t)(CNA_KEY_D6) == INT64_C(54), "CNA_KEY_D6 value");
_Static_assert((int64_t)(CNA_KEY_D7) == INT64_C(55), "CNA_KEY_D7 value");
_Static_assert((int64_t)(CNA_KEY_D8) == INT64_C(56), "CNA_KEY_D8 value");
_Static_assert((int64_t)(CNA_KEY_D9) == INT64_C(57), "CNA_KEY_D9 value");
_Static_assert((int64_t)(CNA_KEY_DECIMAL) == INT64_C(110), "CNA_KEY_DECIMAL value");
_Static_assert((int64_t)(CNA_KEY_DELETE) == INT64_C(46), "CNA_KEY_DELETE value");
_Static_assert((int64_t)(CNA_KEY_DIVIDE) == INT64_C(111), "CNA_KEY_DIVIDE value");
_Static_assert((int64_t)(CNA_KEY_DOWN) == INT64_C(40), "CNA_KEY_DOWN value");
_Static_assert((int64_t)(CNA_KEY_E) == INT64_C(69), "CNA_KEY_E value");
_Static_assert((int64_t)(CNA_KEY_END) == INT64_C(35), "CNA_KEY_END value");
_Static_assert((int64_t)(CNA_KEY_ENTER) == INT64_C(13), "CNA_KEY_ENTER value");
_Static_assert((int64_t)(CNA_KEY_ERASE_EOF) == INT64_C(249), "CNA_KEY_ERASE_EOF value");
_Static_assert((int64_t)(CNA_KEY_ESCAPE) == INT64_C(27), "CNA_KEY_ESCAPE value");
_Static_assert((int64_t)(CNA_KEY_EXECUTE) == INT64_C(43), "CNA_KEY_EXECUTE value");
_Static_assert((int64_t)(CNA_KEY_EXSEL) == INT64_C(248), "CNA_KEY_EXSEL value");
_Static_assert((int64_t)(CNA_KEY_F) == INT64_C(70), "CNA_KEY_F value");
_Static_assert((int64_t)(CNA_KEY_F1) == INT64_C(112), "CNA_KEY_F1 value");
_Static_assert((int64_t)(CNA_KEY_F10) == INT64_C(121), "CNA_KEY_F10 value");
_Static_assert((int64_t)(CNA_KEY_F11) == INT64_C(122), "CNA_KEY_F11 value");
_Static_assert((int64_t)(CNA_KEY_F12) == INT64_C(123), "CNA_KEY_F12 value");
_Static_assert((int64_t)(CNA_KEY_F13) == INT64_C(124), "CNA_KEY_F13 value");
_Static_assert((int64_t)(CNA_KEY_F14) == INT64_C(125), "CNA_KEY_F14 value");
_Static_assert((int64_t)(CNA_KEY_F15) == INT64_C(126), "CNA_KEY_F15 value");
_Static_assert((int64_t)(CNA_KEY_F16) == INT64_C(127), "CNA_KEY_F16 value");
_Static_assert((int64_t)(CNA_KEY_F17) == INT64_C(128), "CNA_KEY_F17 value");
_Static_assert((int64_t)(CNA_KEY_F18) == INT64_C(129), "CNA_KEY_F18 value");
_Static_assert((int64_t)(CNA_KEY_F19) == INT64_C(130), "CNA_KEY_F19 value");
_Static_assert((int64_t)(CNA_KEY_F2) == INT64_C(113), "CNA_KEY_F2 value");
_Static_assert((int64_t)(CNA_KEY_F20) == INT64_C(131), "CNA_KEY_F20 value");
_Static_assert((int64_t)(CNA_KEY_F21) == INT64_C(132), "CNA_KEY_F21 value");
_Static_assert((int64_t)(CNA_KEY_F22) == INT64_C(133), "CNA_KEY_F22 value");
_Static_assert((int64_t)(CNA_KEY_F23) == INT64_C(134), "CNA_KEY_F23 value");
_Static_assert((int64_t)(CNA_KEY_F24) == INT64_C(135), "CNA_KEY_F24 value");
_Static_assert((int64_t)(CNA_KEY_F3) == INT64_C(114), "CNA_KEY_F3 value");
_Static_assert((int64_t)(CNA_KEY_F4) == INT64_C(115), "CNA_KEY_F4 value");
_Static_assert((int64_t)(CNA_KEY_F5) == INT64_C(116), "CNA_KEY_F5 value");
_Static_assert((int64_t)(CNA_KEY_F6) == INT64_C(117), "CNA_KEY_F6 value");
_Static_assert((int64_t)(CNA_KEY_F7) == INT64_C(118), "CNA_KEY_F7 value");
_Static_assert((int64_t)(CNA_KEY_F8) == INT64_C(119), "CNA_KEY_F8 value");
_Static_assert((int64_t)(CNA_KEY_F9) == INT64_C(120), "CNA_KEY_F9 value");
_Static_assert((int64_t)(CNA_KEY_G) == INT64_C(71), "CNA_KEY_G value");
_Static_assert((int64_t)(CNA_KEY_H) == INT64_C(72), "CNA_KEY_H value");
_Static_assert((int64_t)(CNA_KEY_HELP) == INT64_C(47), "CNA_KEY_HELP value");
_Static_assert((int64_t)(CNA_KEY_HOME) == INT64_C(36), "CNA_KEY_HOME value");
_Static_assert((int64_t)(CNA_KEY_I) == INT64_C(73), "CNA_KEY_I value");
_Static_assert((int64_t)(CNA_KEY_IME_CONVERT) == INT64_C(28), "CNA_KEY_IME_CONVERT value");
_Static_assert((int64_t)(CNA_KEY_IME_NO_CONVERT) == INT64_C(29), "CNA_KEY_IME_NO_CONVERT value");
_Static_assert((int64_t)(CNA_KEY_INSERT) == INT64_C(45), "CNA_KEY_INSERT value");
_Static_assert((int64_t)(CNA_KEY_J) == INT64_C(74), "CNA_KEY_J value");
_Static_assert((int64_t)(CNA_KEY_K) == INT64_C(75), "CNA_KEY_K value");
_Static_assert((int64_t)(CNA_KEY_KANA) == INT64_C(21), "CNA_KEY_KANA value");
_Static_assert((int64_t)(CNA_KEY_KANJI) == INT64_C(25), "CNA_KEY_KANJI value");
_Static_assert((int64_t)(CNA_KEY_L) == INT64_C(76), "CNA_KEY_L value");
_Static_assert((int64_t)(CNA_KEY_LAUNCH_APPLICATION1) == INT64_C(182), "CNA_KEY_LAUNCH_APPLICATION1 value");
_Static_assert((int64_t)(CNA_KEY_LAUNCH_APPLICATION2) == INT64_C(183), "CNA_KEY_LAUNCH_APPLICATION2 value");
_Static_assert((int64_t)(CNA_KEY_LAUNCH_MAIL) == INT64_C(180), "CNA_KEY_LAUNCH_MAIL value");
_Static_assert((int64_t)(CNA_KEY_LEFT) == INT64_C(37), "CNA_KEY_LEFT value");
_Static_assert((int64_t)(CNA_KEY_LEFT_ALT) == INT64_C(164), "CNA_KEY_LEFT_ALT value");
_Static_assert((int64_t)(CNA_KEY_LEFT_CONTROL) == INT64_C(162), "CNA_KEY_LEFT_CONTROL value");
_Static_assert((int64_t)(CNA_KEY_LEFT_SHIFT) == INT64_C(160), "CNA_KEY_LEFT_SHIFT value");
_Static_assert((int64_t)(CNA_KEY_LEFT_WINDOWS) == INT64_C(91), "CNA_KEY_LEFT_WINDOWS value");
_Static_assert((int64_t)(CNA_KEY_M) == INT64_C(77), "CNA_KEY_M value");
_Static_assert((int64_t)(CNA_KEY_MEDIA_NEXT_TRACK) == INT64_C(176), "CNA_KEY_MEDIA_NEXT_TRACK value");
_Static_assert((int64_t)(CNA_KEY_MEDIA_PLAY_PAUSE) == INT64_C(179), "CNA_KEY_MEDIA_PLAY_PAUSE value");
_Static_assert((int64_t)(CNA_KEY_MEDIA_PREVIOUS_TRACK) == INT64_C(177), "CNA_KEY_MEDIA_PREVIOUS_TRACK value");
_Static_assert((int64_t)(CNA_KEY_MEDIA_STOP) == INT64_C(178), "CNA_KEY_MEDIA_STOP value");
_Static_assert((int64_t)(CNA_KEY_MULTIPLY) == INT64_C(106), "CNA_KEY_MULTIPLY value");
_Static_assert((int64_t)(CNA_KEY_N) == INT64_C(78), "CNA_KEY_N value");
_Static_assert((int64_t)(CNA_KEY_NONE) == INT64_C(0), "CNA_KEY_NONE value");
_Static_assert((int64_t)(CNA_KEY_NUM_LOCK) == INT64_C(144), "CNA_KEY_NUM_LOCK value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD0) == INT64_C(96), "CNA_KEY_NUM_PAD0 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD1) == INT64_C(97), "CNA_KEY_NUM_PAD1 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD2) == INT64_C(98), "CNA_KEY_NUM_PAD2 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD3) == INT64_C(99), "CNA_KEY_NUM_PAD3 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD4) == INT64_C(100), "CNA_KEY_NUM_PAD4 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD5) == INT64_C(101), "CNA_KEY_NUM_PAD5 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD6) == INT64_C(102), "CNA_KEY_NUM_PAD6 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD7) == INT64_C(103), "CNA_KEY_NUM_PAD7 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD8) == INT64_C(104), "CNA_KEY_NUM_PAD8 value");
_Static_assert((int64_t)(CNA_KEY_NUM_PAD9) == INT64_C(105), "CNA_KEY_NUM_PAD9 value");
_Static_assert((int64_t)(CNA_KEY_O) == INT64_C(79), "CNA_KEY_O value");
_Static_assert((int64_t)(CNA_KEY_OEM8) == INT64_C(223), "CNA_KEY_OEM8 value");
_Static_assert((int64_t)(CNA_KEY_OEM_AUTO) == INT64_C(243), "CNA_KEY_OEM_AUTO value");
_Static_assert((int64_t)(CNA_KEY_OEM_BACKSLASH) == INT64_C(226), "CNA_KEY_OEM_BACKSLASH value");
_Static_assert((int64_t)(CNA_KEY_OEM_CLEAR) == INT64_C(254), "CNA_KEY_OEM_CLEAR value");
_Static_assert((int64_t)(CNA_KEY_OEM_CLOSE_BRACKETS) == INT64_C(221), "CNA_KEY_OEM_CLOSE_BRACKETS value");
_Static_assert((int64_t)(CNA_KEY_OEM_COMMA) == INT64_C(188), "CNA_KEY_OEM_COMMA value");
_Static_assert((int64_t)(CNA_KEY_OEM_COPY) == INT64_C(242), "CNA_KEY_OEM_COPY value");
_Static_assert((int64_t)(CNA_KEY_OEM_ENL_W) == INT64_C(244), "CNA_KEY_OEM_ENL_W value");
_Static_assert((int64_t)(CNA_KEY_OEM_MINUS) == INT64_C(189), "CNA_KEY_OEM_MINUS value");
_Static_assert((int64_t)(CNA_KEY_OEM_OPEN_BRACKETS) == INT64_C(219), "CNA_KEY_OEM_OPEN_BRACKETS value");
_Static_assert((int64_t)(CNA_KEY_OEM_PERIOD) == INT64_C(190), "CNA_KEY_OEM_PERIOD value");
_Static_assert((int64_t)(CNA_KEY_OEM_PIPE) == INT64_C(220), "CNA_KEY_OEM_PIPE value");
_Static_assert((int64_t)(CNA_KEY_OEM_PLUS) == INT64_C(187), "CNA_KEY_OEM_PLUS value");
_Static_assert((int64_t)(CNA_KEY_OEM_QUESTION) == INT64_C(191), "CNA_KEY_OEM_QUESTION value");
_Static_assert((int64_t)(CNA_KEY_OEM_QUOTES) == INT64_C(222), "CNA_KEY_OEM_QUOTES value");
_Static_assert((int64_t)(CNA_KEY_OEM_SEMICOLON) == INT64_C(186), "CNA_KEY_OEM_SEMICOLON value");
_Static_assert((int64_t)(CNA_KEY_OEM_TILDE) == INT64_C(192), "CNA_KEY_OEM_TILDE value");
_Static_assert((int64_t)(CNA_KEY_P) == INT64_C(80), "CNA_KEY_P value");
_Static_assert((int64_t)(CNA_KEY_PA1) == INT64_C(253), "CNA_KEY_PA1 value");
_Static_assert((int64_t)(CNA_KEY_PAGE_DOWN) == INT64_C(34), "CNA_KEY_PAGE_DOWN value");
_Static_assert((int64_t)(CNA_KEY_PAGE_UP) == INT64_C(33), "CNA_KEY_PAGE_UP value");
_Static_assert((int64_t)(CNA_KEY_PAUSE) == INT64_C(19), "CNA_KEY_PAUSE value");
_Static_assert((int64_t)(CNA_KEY_PLAY) == INT64_C(250), "CNA_KEY_PLAY value");
_Static_assert((int64_t)(CNA_KEY_PRINT) == INT64_C(42), "CNA_KEY_PRINT value");
_Static_assert((int64_t)(CNA_KEY_PRINT_SCREEN) == INT64_C(44), "CNA_KEY_PRINT_SCREEN value");
_Static_assert((int64_t)(CNA_KEY_PROCESS_KEY) == INT64_C(229), "CNA_KEY_PROCESS_KEY value");
_Static_assert((int64_t)(CNA_KEY_Q) == INT64_C(81), "CNA_KEY_Q value");
_Static_assert((int64_t)(CNA_KEY_R) == INT64_C(82), "CNA_KEY_R value");
_Static_assert((int64_t)(CNA_KEY_RIGHT) == INT64_C(39), "CNA_KEY_RIGHT value");
_Static_assert((int64_t)(CNA_KEY_RIGHT_ALT) == INT64_C(165), "CNA_KEY_RIGHT_ALT value");
_Static_assert((int64_t)(CNA_KEY_RIGHT_CONTROL) == INT64_C(163), "CNA_KEY_RIGHT_CONTROL value");
_Static_assert((int64_t)(CNA_KEY_RIGHT_SHIFT) == INT64_C(161), "CNA_KEY_RIGHT_SHIFT value");
_Static_assert((int64_t)(CNA_KEY_RIGHT_WINDOWS) == INT64_C(92), "CNA_KEY_RIGHT_WINDOWS value");
_Static_assert((int64_t)(CNA_KEY_S) == INT64_C(83), "CNA_KEY_S value");
_Static_assert((int64_t)(CNA_KEY_SCROLL) == INT64_C(145), "CNA_KEY_SCROLL value");
_Static_assert((int64_t)(CNA_KEY_SELECT) == INT64_C(41), "CNA_KEY_SELECT value");
_Static_assert((int64_t)(CNA_KEY_SELECT_MEDIA) == INT64_C(181), "CNA_KEY_SELECT_MEDIA value");
_Static_assert((int64_t)(CNA_KEY_SEPARATOR) == INT64_C(108), "CNA_KEY_SEPARATOR value");
_Static_assert((int64_t)(CNA_KEY_SLEEP) == INT64_C(95), "CNA_KEY_SLEEP value");
_Static_assert((int64_t)(CNA_KEY_SPACE) == INT64_C(32), "CNA_KEY_SPACE value");
_Static_assert((int64_t)(CNA_KEY_STATE_DOWN) == INT64_C(1), "CNA_KEY_STATE_DOWN value");
_Static_assert((int64_t)(CNA_KEY_STATE_UP) == INT64_C(0), "CNA_KEY_STATE_UP value");
_Static_assert((int64_t)(CNA_KEY_SUBTRACT) == INT64_C(109), "CNA_KEY_SUBTRACT value");
_Static_assert((int64_t)(CNA_KEY_T) == INT64_C(84), "CNA_KEY_T value");
_Static_assert((int64_t)(CNA_KEY_TAB) == INT64_C(9), "CNA_KEY_TAB value");
_Static_assert((int64_t)(CNA_KEY_U) == INT64_C(85), "CNA_KEY_U value");
_Static_assert((int64_t)(CNA_KEY_UP) == INT64_C(38), "CNA_KEY_UP value");
_Static_assert((int64_t)(CNA_KEY_V) == INT64_C(86), "CNA_KEY_V value");
_Static_assert((int64_t)(CNA_KEY_VOLUME_DOWN) == INT64_C(174), "CNA_KEY_VOLUME_DOWN value");
_Static_assert((int64_t)(CNA_KEY_VOLUME_MUTE) == INT64_C(173), "CNA_KEY_VOLUME_MUTE value");
_Static_assert((int64_t)(CNA_KEY_VOLUME_UP) == INT64_C(175), "CNA_KEY_VOLUME_UP value");
_Static_assert((int64_t)(CNA_KEY_W) == INT64_C(87), "CNA_KEY_W value");
_Static_assert((int64_t)(CNA_KEY_X) == INT64_C(88), "CNA_KEY_X value");
_Static_assert((int64_t)(CNA_KEY_Y) == INT64_C(89), "CNA_KEY_Y value");
_Static_assert((int64_t)(CNA_KEY_Z) == INT64_C(90), "CNA_KEY_Z value");
_Static_assert((int64_t)(CNA_KEY_ZOOM) == INT64_C(251), "CNA_KEY_ZOOM value");
_Static_assert((int64_t)(CNA_MOUSE_BUTTON_LEFT) == INT64_C(1), "CNA_MOUSE_BUTTON_LEFT value");
_Static_assert((int64_t)(CNA_MOUSE_BUTTON_MIDDLE) == INT64_C(2), "CNA_MOUSE_BUTTON_MIDDLE value");
_Static_assert((int64_t)(CNA_MOUSE_BUTTON_NONE) == INT64_C(0), "CNA_MOUSE_BUTTON_NONE value");
_Static_assert((int64_t)(CNA_MOUSE_BUTTON_RIGHT) == INT64_C(4), "CNA_MOUSE_BUTTON_RIGHT value");
_Static_assert((int64_t)(CNA_MOUSE_BUTTON_X1) == INT64_C(8), "CNA_MOUSE_BUTTON_X1 value");
_Static_assert((int64_t)(CNA_MOUSE_BUTTON_X2) == INT64_C(16), "CNA_MOUSE_BUTTON_X2 value");
_Static_assert((int64_t)(CNA_PLAYER_INDEX_FOUR) == INT64_C(3), "CNA_PLAYER_INDEX_FOUR value");
_Static_assert((int64_t)(CNA_PLAYER_INDEX_ONE) == INT64_C(0), "CNA_PLAYER_INDEX_ONE value");
_Static_assert((int64_t)(CNA_PLAYER_INDEX_THREE) == INT64_C(2), "CNA_PLAYER_INDEX_THREE value");
_Static_assert((int64_t)(CNA_PLAYER_INDEX_TWO) == INT64_C(1), "CNA_PLAYER_INDEX_TWO value");
_Static_assert((int64_t)(CNA_RESULT_BUFFER_TOO_SMALL) == INT64_C(14), "CNA_RESULT_BUFFER_TOO_SMALL value");
_Static_assert((int64_t)(CNA_RESULT_CALLBACK) == INT64_C(9), "CNA_RESULT_CALLBACK value");
_Static_assert((int64_t)(CNA_RESULT_ENCODING) == INT64_C(11), "CNA_RESULT_ENCODING value");
_Static_assert((int64_t)(CNA_RESULT_INTERNAL) == INT64_C(12), "CNA_RESULT_INTERNAL value");
_Static_assert((int64_t)(CNA_RESULT_INVALID_ARGUMENT) == INT64_C(1), "CNA_RESULT_INVALID_ARGUMENT value");
_Static_assert((int64_t)(CNA_RESULT_INVALID_HANDLE) == INT64_C(2), "CNA_RESULT_INVALID_HANDLE value");
_Static_assert((int64_t)(CNA_RESULT_INVALID_STATE) == INT64_C(3), "CNA_RESULT_INVALID_STATE value");
_Static_assert((int64_t)(CNA_RESULT_IO) == INT64_C(5), "CNA_RESULT_IO value");
_Static_assert((int64_t)(CNA_RESULT_NOT_SUPPORTED) == INT64_C(6), "CNA_RESULT_NOT_SUPPORTED value");
_Static_assert((int64_t)(CNA_RESULT_OUT_OF_MEMORY) == INT64_C(4), "CNA_RESULT_OUT_OF_MEMORY value");
_Static_assert((int64_t)(CNA_RESULT_OVERFLOW) == INT64_C(10), "CNA_RESULT_OVERFLOW value");
_Static_assert((int64_t)(CNA_RESULT_PLATFORM) == INT64_C(7), "CNA_RESULT_PLATFORM value");
_Static_assert((int64_t)(CNA_RESULT_SHUTTING_DOWN) == INT64_C(13), "CNA_RESULT_SHUTTING_DOWN value");
_Static_assert((int64_t)(CNA_RESULT_SUCCESS) == INT64_C(0), "CNA_RESULT_SUCCESS value");
_Static_assert((int64_t)(CNA_RESULT_THREAD) == INT64_C(8), "CNA_RESULT_THREAD value");
_Static_assert((int64_t)(CNA_SPRITE_EFFECT_FLIP_HORIZONTALLY) == INT64_C(1), "CNA_SPRITE_EFFECT_FLIP_HORIZONTALLY value");
_Static_assert((int64_t)(CNA_SPRITE_EFFECT_FLIP_VERTICALLY) == INT64_C(2), "CNA_SPRITE_EFFECT_FLIP_VERTICALLY value");
_Static_assert((int64_t)(CNA_SPRITE_EFFECT_NONE) == INT64_C(0), "CNA_SPRITE_EFFECT_NONE value");
_Static_assert((int64_t)(CNA_SPRITE_SORT_MODE_BACK_TO_FRONT) == INT64_C(3), "CNA_SPRITE_SORT_MODE_BACK_TO_FRONT value");
_Static_assert((int64_t)(CNA_SPRITE_SORT_MODE_DEFERRED) == INT64_C(0), "CNA_SPRITE_SORT_MODE_DEFERRED value");
_Static_assert((int64_t)(CNA_SPRITE_SORT_MODE_FRONT_TO_BACK) == INT64_C(4), "CNA_SPRITE_SORT_MODE_FRONT_TO_BACK value");
_Static_assert((int64_t)(CNA_SPRITE_SORT_MODE_IMMEDIATE) == INT64_C(1), "CNA_SPRITE_SORT_MODE_IMMEDIATE value");
_Static_assert((int64_t)(CNA_SPRITE_SORT_MODE_TEXTURE) == INT64_C(2), "CNA_SPRITE_SORT_MODE_TEXTURE value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_ALPHA8) == INT64_C(12), "CNA_SURFACE_FORMAT_ALPHA8 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_BC7_EXT) == INT64_C(23), "CNA_SURFACE_FORMAT_BC7_EXT value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_BC7_SRGB_EXT) == INT64_C(24), "CNA_SURFACE_FORMAT_BC7_SRGB_EXT value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_BGR565) == INT64_C(1), "CNA_SURFACE_FORMAT_BGR565 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_BGRA4444) == INT64_C(3), "CNA_SURFACE_FORMAT_BGRA4444 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_BGRA5551) == INT64_C(2), "CNA_SURFACE_FORMAT_BGRA5551 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_BYTE_EXT) == INT64_C(25), "CNA_SURFACE_FORMAT_BYTE_EXT value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_COLOR) == INT64_C(0), "CNA_SURFACE_FORMAT_COLOR value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_COLOR_BGRA_EXT) == INT64_C(20), "CNA_SURFACE_FORMAT_COLOR_BGRA_EXT value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_COLOR_SRGB_EXT) == INT64_C(21), "CNA_SURFACE_FORMAT_COLOR_SRGB_EXT value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_DXT1) == INT64_C(4), "CNA_SURFACE_FORMAT_DXT1 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_DXT3) == INT64_C(5), "CNA_SURFACE_FORMAT_DXT3 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_DXT5) == INT64_C(6), "CNA_SURFACE_FORMAT_DXT5 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_DXT5_SRGB_EXT) == INT64_C(22), "CNA_SURFACE_FORMAT_DXT5_SRGB_EXT value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_HALF_SINGLE) == INT64_C(16), "CNA_SURFACE_FORMAT_HALF_SINGLE value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_HALF_VECTOR2) == INT64_C(17), "CNA_SURFACE_FORMAT_HALF_VECTOR2 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_HALF_VECTOR4) == INT64_C(18), "CNA_SURFACE_FORMAT_HALF_VECTOR4 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_HDR_BLENDABLE) == INT64_C(19), "CNA_SURFACE_FORMAT_HDR_BLENDABLE value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_NORMALIZED_BYTE2) == INT64_C(7), "CNA_SURFACE_FORMAT_NORMALIZED_BYTE2 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_NORMALIZED_BYTE4) == INT64_C(8), "CNA_SURFACE_FORMAT_NORMALIZED_BYTE4 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_RG32) == INT64_C(10), "CNA_SURFACE_FORMAT_RG32 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_RGBA1010102) == INT64_C(9), "CNA_SURFACE_FORMAT_RGBA1010102 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_RGBA64) == INT64_C(11), "CNA_SURFACE_FORMAT_RGBA64 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_SINGLE) == INT64_C(13), "CNA_SURFACE_FORMAT_SINGLE value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_USHORT_EXT) == INT64_C(26), "CNA_SURFACE_FORMAT_USHORT_EXT value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_VECTOR2) == INT64_C(14), "CNA_SURFACE_FORMAT_VECTOR2 value");
_Static_assert((int64_t)(CNA_SURFACE_FORMAT_VECTOR4) == INT64_C(15), "CNA_SURFACE_FORMAT_VECTOR4 value");
_Static_assert((int64_t)(CNA_TRUE) == INT64_C(1), "CNA_TRUE value");

int cna_lisp_probe_ok(void) { return 1; }
